import type { TimeBlock, DailySchedule } from '../types/database';

// Mock schedule based on Appendix A: "Map Makers & Explorers" Monday
export const MOCK_THEME = "Map Makers & Explorers 🗺️";

export const MOCK_TIME_BLOCKS: Omit<TimeBlock, 'id' | 'daily_schedule_id' | 'created_at' | 'updated_at'>[] = [
  {
    start_time: '09:00',
    end_time: '09:30',
    category: 'sibling_play',
    activity_name: 'Group Play Time - Treasure Map Walk',
    description: 'Hide 5 "treasures" around basement. Nobel draws a map for his sister to follow. She toddles along while he guides her.',
    materials_needed: ['paper', 'crayons', 'small toys to hide'],
    learning_objective: 'Spatial awareness, leadership skills, and practicing giving directions',
    difficulty: 'moderate',
    tags: ['social', 'creative', 'spatial'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '09:30',
    end_time: '10:30',
    category: 'independent_play',
    activity_name: 'Independent Play - Lego City Builder',
    description: 'Build a city with Legos. Challenge: make buildings of specific heights (5 blocks, 10 blocks). Count windows and doors.',
    materials_needed: ['Legos'],
    learning_objective: 'Counting practice, following multi-step instructions, creative building',
    difficulty: 'moderate',
    tags: ['building', 'math', 'creative'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '10:30',
    end_time: '11:15',
    category: 'focused_learning',
    activity_name: 'Focused Learning - Reading: Me on the Map',
    description: 'Read "Me on the Map" by Joan Sweeney. Discussion: Where is our house? Our street? Virginia? Activity: Draw a simple map of our house.',
    materials_needed: ['book: Me on the Map', 'paper', 'crayons'],
    learning_objective: 'Reading comprehension, understanding geographic scale from room → house → street → city → state → country',
    difficulty: 'moderate',
    tags: ['reading', 'geography', 'discussion'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '11:15',
    end_time: '11:45',
    category: 'focused_learning',
    activity_name: 'Focused Learning - Map Coordinate Game',
    description: 'Simple grid game. "Go 3 squares right, 2 squares up. What did you find?" Introduce basic coordinate concepts with a treasure grid.',
    materials_needed: ['printed grid', 'stickers'],
    learning_objective: 'Introduction to coordinate systems, following directional instructions, counting',
    difficulty: 'challenging',
    tags: ['math', 'spatial', 'problem-solving'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '11:45',
    end_time: '12:00',
    category: 'independent_play',
    activity_name: 'Independent Play - Basketball Shooting Challenge',
    description: 'Basketball shooting: count makes vs. misses. "Can you make 7 out of 10?"',
    materials_needed: ['basketball hoop', 'basketball'],
    learning_objective: 'Gross motor skills, counting, understanding fractions/ratios informally',
    difficulty: 'easy',
    tags: ['physical', 'math', 'motor'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '12:00',
    end_time: '12:15',
    category: 'amharic',
    activity_name: 'Amharic Practice - Direction Words',
    description: 'Learn "left" (ግራ), "right" (ቀኝ), "up" (ላይ), "down" (ታች). Play Simon Says in Amharic with directions.',
    materials_needed: [],
    learning_objective: 'Amharic vocabulary for directions, listening comprehension, TPR (Total Physical Response)',
    difficulty: 'moderate',
    tags: ['amharic', 'vocabulary', 'physical'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '12:15',
    end_time: '13:00',
    category: 'lunch',
    activity_name: 'Lunch',
    description: '',
    materials_needed: [],
    learning_objective: '',
    difficulty: 'easy',
    tags: ['meal'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '13:00',
    end_time: '14:15',
    category: 'sibling_play',
    activity_name: 'Creative Time - Cardboard Map Project',
    description: 'Build a 3D map of the neighborhood using cardboard, tape, markers. Sister can help with stickers. Nobel labels streets and landmarks.',
    materials_needed: ['cardboard', 'tape', 'markers', 'stickers', 'scissors'],
    learning_objective: 'Spatial reasoning, fine motor skills, collaborative play, real-world geography connection',
    difficulty: 'challenging',
    tags: ['creative', 'building', 'geography', 'social'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '14:15',
    end_time: '14:45',
    category: 'outdoor',
    activity_name: 'Outdoor Time - Neighborhood Map Walk',
    description: 'Walk the actual route they mapped. Nobel points out landmarks. Count houses, trees, mailboxes.',
    materials_needed: [],
    learning_objective: 'Connecting abstract maps to real world, observation skills, counting practice',
    difficulty: 'easy',
    tags: ['outdoor', 'geography', 'math', 'observation'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '14:45',
    end_time: '15:45',
    category: 'rest',
    activity_name: 'Rest Time - Quiet Reading',
    description: 'Quiet time in bedroom. Suggested reading: "National Geographic Little Kids First Big Book of the World"',
    materials_needed: ['book suggestion: National Geographic Little Kids First Big Book of the World'],
    learning_objective: 'Self-regulation, independent reading practice, rest and recharge',
    difficulty: 'easy',
    tags: ['rest', 'reading', 'independent'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '15:45',
    end_time: '16:00',
    category: 'amharic',
    activity_name: 'Amharic Practice - Colors with Lego Blocks',
    description: 'Review colors in Amharic using Lego blocks. "Give me the ቀይ (red) block."',
    materials_needed: ['Lego blocks in various colors'],
    learning_objective: 'Amharic color vocabulary reinforcement, listening comprehension',
    difficulty: 'easy',
    tags: ['amharic', 'vocabulary', 'colors'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '16:00',
    end_time: '17:00',
    category: 'independent_play',
    activity_name: 'Creative Time - Pirate Treasure Map Art',
    description: 'Make a "pirate treasure map" — tear edges, tea-stain paper (with help), draw compass rose, X marks the spot.',
    materials_needed: ['paper', 'tea bags', 'markers', 'crayons'],
    learning_objective: 'Fine motor skills, creativity, learning about compass directions (N, S, E, W)',
    difficulty: 'moderate',
    tags: ['creative', 'art', 'geography', 'fine-motor'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '17:00',
    end_time: '18:15',
    category: 'independent_play',
    activity_name: 'Independent Play - Free Basement Play',
    description: 'Basement free play. Available: trampoline, slides, blocks, keyboard.',
    materials_needed: [],
    learning_objective: 'Unstructured play, creativity, physical activity, self-directed exploration',
    difficulty: 'easy',
    tags: ['free-play', 'physical', 'creative'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '18:15',
    end_time: '18:30',
    category: 'cleanup',
    activity_name: 'Routine - Map Explorer Cleanup Mission',
    description: '"Map Explorer cleanup mission: can you find and put away 20 items in 2 minutes?"',
    materials_needed: ['timer'],
    learning_objective: 'Responsibility, counting, time awareness, organization skills',
    difficulty: 'easy',
    tags: ['routine', 'counting', 'responsibility'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '18:30',
    end_time: '19:30',
    category: 'dinner',
    activity_name: 'Dinner',
    description: '',
    materials_needed: [],
    learning_objective: '',
    difficulty: 'easy',
    tags: ['meal'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '19:30',
    end_time: '20:00',
    category: 'routine',
    activity_name: 'Routine - Bath & Bedtime Prep',
    description: 'Bath and preparation for bed.',
    materials_needed: [],
    learning_objective: 'Self-care routine, independence',
    difficulty: 'easy',
    tags: ['routine', 'self-care'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
  {
    start_time: '20:00',
    end_time: '21:00',
    category: 'reading',
    activity_name: 'Reading Time - Independent Chapter Book',
    description: 'Nobel reads independently in his room. Suggested: Continue chapter book or explore atlas.',
    materials_needed: ['books', 'atlas'],
    learning_objective: 'Reading fluency, love of reading, independence',
    difficulty: 'easy',
    tags: ['reading', 'independent'],
    status: 'pending',
    parent_notes: null,
    completed_at: null,
  },
];

export function getMockSchedule(date: string, childId: string): {
  schedule: Omit<DailySchedule, 'id' | 'created_at' | 'updated_at'>;
  timeBlocks: Omit<TimeBlock, 'id' | 'daily_schedule_id' | 'created_at' | 'updated_at'>[];
  theme: string;
} {
  return {
    schedule: {
      weekly_plan_id: null,
      child_id: childId,
      date,
      generated_at: new Date().toISOString(),
      adjusted_at: null,
      status: 'active',
    },
    timeBlocks: MOCK_TIME_BLOCKS,
    theme: MOCK_THEME,
  };
}

// Alternative themes for variety
export const MOCK_THEMES = [
  "Map Makers & Explorers 🗺️",
  "Ocean Adventures 🌊",
  "Space Explorers 🚀",
  "Dinosaur Discovery 🦕",
  "Garden Scientists 🌱",
  "Building Engineers 🏗️",
  "Music Makers 🎵",
  "Animal Kingdom 🦁",
];

export function getRandomTheme(): string {
  return MOCK_THEMES[Math.floor(Math.random() * MOCK_THEMES.length)];
}
